SET ROLE live_project_owner;

CREATE TABLE public.tour_attrs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_title text NOT NULL,
    url text,
    description text,
    CONSTRAINT tour_attrs_title_not_blank CHECK (btrim(tour_title) <> ''),
    CONSTRAINT tour_attrs_url_not_blank CHECK (url IS NULL OR btrim(url) <> '')
);

CREATE TABLE public.tour_bands (
    tour_id integer NOT NULL
        REFERENCES public.tour_attrs(id) ON DELETE CASCADE,
    band_id integer NOT NULL
        REFERENCES public.band_attrs(id) ON DELETE RESTRICT,
    display_order integer NOT NULL CHECK (display_order > 0),
    PRIMARY KEY (tour_id, band_id),
    UNIQUE (tour_id, display_order)
);

CREATE TABLE public.tour_lives (
    tour_id integer NOT NULL
        REFERENCES public.tour_attrs(id) ON DELETE CASCADE,
    live_id integer NOT NULL
        REFERENCES public.live_attrs(id) ON DELETE CASCADE,
    stop_order integer NOT NULL CHECK (stop_order > 0),
    stop_label text,
    PRIMARY KEY (tour_id, live_id),
    UNIQUE (live_id),
    UNIQUE (tour_id, stop_order),
    CONSTRAINT tour_lives_label_not_blank
        CHECK (stop_label IS NULL OR btrim(stop_label) <> '')
);

RESET ROLE;

GRANT SELECT ON TABLE public.tour_attrs, public.tour_bands, public.tour_lives
    TO live_project_ro;
GRANT SELECT, INSERT, UPDATE ON TABLE public.tour_attrs, public.tour_bands, public.tour_lives
    TO live_project_super_ro;
GRANT DELETE ON TABLE public.tour_bands, public.tour_lives
    TO live_project_super_ro;

GRANT SELECT ON SEQUENCE public.tour_attrs_id_seq TO live_project_ro;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.tour_attrs_id_seq TO live_project_super_ro;
