SET ROLE live_project_owner;

CREATE TABLE public.performance_group_attrs (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_title text NOT NULL,
    CONSTRAINT performance_group_attrs_title_not_blank
        CHECK (btrim(group_title) <> '')
);

CREATE TABLE public.performance_group_lives (
    group_id integer NOT NULL
        REFERENCES public.performance_group_attrs(id) ON DELETE CASCADE,
    live_id integer NOT NULL
        REFERENCES public.live_attrs(id) ON DELETE CASCADE,
    PRIMARY KEY (group_id, live_id),
    UNIQUE (live_id)
);

RESET ROLE;

GRANT SELECT ON TABLE public.performance_group_attrs, public.performance_group_lives
    TO live_project_ro;
GRANT SELECT, INSERT, UPDATE ON TABLE public.performance_group_attrs, public.performance_group_lives
    TO live_project_super_ro;
GRANT DELETE ON TABLE public.performance_group_lives
    TO live_project_super_ro;

GRANT SELECT ON SEQUENCE public.performance_group_attrs_id_seq TO live_project_ro;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.performance_group_attrs_id_seq TO live_project_super_ro;
