SET ROLE live_project_owner;

ALTER TABLE public.live_attrs
    ADD COLUMN event_status text NOT NULL DEFAULT 'scheduled',
    ADD COLUMN status_note text,
    ADD CONSTRAINT live_attrs_event_status_check
        CHECK (event_status IN ('scheduled', 'postponed', 'cancelled'));

CREATE TABLE public.live_schedule_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    live_id integer NOT NULL REFERENCES public.live_attrs(id),
    previous_live_date date NOT NULL,
    previous_opening_time time with time zone NOT NULL,
    previous_start_time time with time zone NOT NULL,
    previous_venue_id integer NOT NULL REFERENCES public.venue_list(id),
    changed_at timestamp with time zone NOT NULL DEFAULT now(),
    changed_by bigint REFERENCES public.app_users(id) ON DELETE SET NULL,
    note text
);

CREATE INDEX live_schedule_history_live_id_changed_at_idx
    ON public.live_schedule_history (live_id, changed_at, id);

RESET ROLE;

GRANT SELECT ON TABLE public.live_schedule_history TO live_project_ro;
GRANT SELECT, INSERT ON TABLE public.live_schedule_history TO live_project_super_ro;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE public.live_schedule_history_id_seq
    TO live_project_super_ro;
