SET ROLE live_project_owner;

CREATE TABLE public.band_name_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id integer NOT NULL
        REFERENCES public.band_attrs(id) ON DELETE RESTRICT,
    band_name text NOT NULL,
    band_abbr text,
    valid_from date,
    valid_to date,
    note text,
    CONSTRAINT band_name_versions_real_band
        CHECK (band_id > 0),
    CONSTRAINT band_name_versions_name_not_blank
        CHECK (btrim(band_name) <> ''),
    CONSTRAINT band_name_versions_abbr_not_blank
        CHECK (band_abbr IS NULL OR btrim(band_abbr) <> ''),
    CONSTRAINT band_name_versions_valid_range
        CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from)
);

CREATE INDEX band_name_versions_band_validity_idx
    ON public.band_name_versions (band_id, valid_from, valid_to, id);
CREATE INDEX band_name_versions_normalized_name_idx
    ON public.band_name_versions (lower(btrim(band_name)), band_id);

CREATE TABLE public.band_lineup_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    band_id integer NOT NULL
        REFERENCES public.band_attrs(id) ON DELETE RESTRICT,
    version_no integer NOT NULL,
    version_label text NOT NULL,
    valid_from date,
    valid_to date,
    predecessor_id bigint,
    change_type text NOT NULL,
    note text,
    CONSTRAINT band_lineup_versions_real_band
        CHECK (band_id > 0),
    CONSTRAINT band_lineup_versions_version_positive
        CHECK (version_no > 0),
    CONSTRAINT band_lineup_versions_unique_no
        UNIQUE (band_id, version_no),
    CONSTRAINT band_lineup_versions_label_not_blank
        CHECK (btrim(version_label) <> ''),
    CONSTRAINT band_lineup_versions_change_type
        CHECK (change_type IN ('initial', 'addition', 'removal', 'replacement', 'correction')),
    CONSTRAINT band_lineup_versions_valid_range
        CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from)
);

ALTER TABLE public.band_lineup_versions
    ADD CONSTRAINT band_lineup_versions_predecessor_fkey
    FOREIGN KEY (predecessor_id)
    REFERENCES public.band_lineup_versions(id)
    ON DELETE RESTRICT;

CREATE INDEX band_lineup_versions_band_validity_idx
    ON public.band_lineup_versions (band_id, valid_from, valid_to, id);
CREATE INDEX band_lineup_versions_predecessor_idx
    ON public.band_lineup_versions (predecessor_id)
    WHERE predecessor_id IS NOT NULL;

CREATE TABLE public.band_lineup_version_members (
    lineup_version_id bigint NOT NULL
        REFERENCES public.band_lineup_versions(id) ON DELETE CASCADE,
    member_name text NOT NULL,
    display_order integer NOT NULL,
    PRIMARY KEY (lineup_version_id, member_name),
    UNIQUE (lineup_version_id, display_order),
    CONSTRAINT band_lineup_version_members_name_not_blank
        CHECK (btrim(member_name) <> ''),
    CONSTRAINT band_lineup_version_members_order_positive
        CHECK (display_order > 0)
);

CREATE TABLE public.live_band_lineup_contexts (
    live_id integer NOT NULL
        REFERENCES public.live_attrs(id) ON DELETE CASCADE,
    band_id integer NOT NULL
        REFERENCES public.band_attrs(id) ON DELETE RESTRICT,
    band_name_version_id bigint NOT NULL
        REFERENCES public.band_name_versions(id) ON DELETE RESTRICT,
    base_lineup_version_id bigint NOT NULL
        REFERENCES public.band_lineup_versions(id) ON DELETE RESTRICT,
    next_lineup_version_id bigint
        REFERENCES public.band_lineup_versions(id) ON DELETE RESTRICT,
    note text,
    PRIMARY KEY (live_id, band_id),
    CONSTRAINT live_band_lineup_contexts_real_band
        CHECK (band_id > 0),
    CONSTRAINT live_band_lineup_contexts_distinct_versions
        CHECK (
            next_lineup_version_id IS NULL
            OR next_lineup_version_id <> base_lineup_version_id
        )
);

CREATE INDEX live_band_lineup_contexts_name_version_idx
    ON public.live_band_lineup_contexts (band_name_version_id);
CREATE INDEX live_band_lineup_contexts_base_version_idx
    ON public.live_band_lineup_contexts (base_lineup_version_id);
CREATE INDEX live_band_lineup_contexts_next_version_idx
    ON public.live_band_lineup_contexts (next_lineup_version_id)
    WHERE next_lineup_version_id IS NOT NULL;

ALTER TABLE public.live_setlist
    ADD CONSTRAINT live_setlist_id_live_id_key UNIQUE (id, live_id);

CREATE TABLE public.live_setlist_band_performances (
    setlist_id uuid NOT NULL,
    live_id integer NOT NULL,
    band_id integer NOT NULL
        REFERENCES public.band_attrs(id) ON DELETE RESTRICT,
    lineup_usage text NOT NULL,
    PRIMARY KEY (setlist_id, band_id),
    FOREIGN KEY (setlist_id, live_id)
        REFERENCES public.live_setlist(id, live_id) ON DELETE CASCADE,
    FOREIGN KEY (live_id, band_id)
        REFERENCES public.live_band_lineup_contexts(live_id, band_id)
        ON DELETE RESTRICT,
    CONSTRAINT live_setlist_band_performances_real_band
        CHECK (band_id > 0),
    CONSTRAINT live_setlist_band_performances_usage
        CHECK (lineup_usage IN ('base', 'next', 'handover'))
);

CREATE INDEX live_setlist_band_performances_live_band_idx
    ON public.live_setlist_band_performances (live_id, band_id);

CREATE TABLE public.live_setlist_band_performance_members (
    setlist_id uuid NOT NULL,
    band_id integer NOT NULL,
    member_name text NOT NULL,
    display_order integer NOT NULL,
    appearance_role text,
    PRIMARY KEY (setlist_id, band_id, member_name),
    UNIQUE (setlist_id, band_id, display_order),
    FOREIGN KEY (setlist_id, band_id)
        REFERENCES public.live_setlist_band_performances(setlist_id, band_id)
        ON DELETE CASCADE,
    CONSTRAINT live_setlist_band_performance_members_name_not_blank
        CHECK (btrim(member_name) <> ''),
    CONSTRAINT live_setlist_band_performance_members_order_positive
        CHECK (display_order > 0),
    CONSTRAINT live_setlist_band_performance_members_role
        CHECK (
            appearance_role IS NULL
            OR appearance_role IN ('former', 'incoming', 'guest', 'support')
        )
);

RESET ROLE;

GRANT SELECT ON TABLE
    public.band_name_versions,
    public.band_lineup_versions,
    public.band_lineup_version_members,
    public.live_band_lineup_contexts,
    public.live_setlist_band_performances,
    public.live_setlist_band_performance_members
TO live_project_ro;

GRANT SELECT, INSERT, UPDATE ON TABLE
    public.band_name_versions,
    public.band_lineup_versions,
    public.band_lineup_version_members,
    public.live_band_lineup_contexts,
    public.live_setlist_band_performances,
    public.live_setlist_band_performance_members
TO live_project_super_ro;

-- 开发整理期的版本修正和完整集合替换只向关系/成员子表开放 DELETE。
GRANT DELETE ON TABLE
    public.band_lineup_version_members,
    public.live_band_lineup_contexts,
    public.live_setlist_band_performances,
    public.live_setlist_band_performance_members
TO live_project_super_ro;

GRANT SELECT ON SEQUENCE
    public.band_name_versions_id_seq,
    public.band_lineup_versions_id_seq
TO live_project_ro;

GRANT USAGE, SELECT, UPDATE ON SEQUENCE
    public.band_name_versions_id_seq,
    public.band_lineup_versions_id_seq
TO live_project_super_ro;
