SET ROLE live_project_owner;

ALTER TABLE public.venue_list
    ADD COLUMN venue_kind text NOT NULL DEFAULT 'physical',
    ADD COLUMN merged_into_venue_id integer
        REFERENCES public.venue_list(id) ON DELETE RESTRICT,
    ADD CONSTRAINT venue_list_kind_check
        CHECK (venue_kind IN ('physical', 'online', 'undisclosed')),
    ADD CONSTRAINT venue_list_merge_not_self
        CHECK (merged_into_venue_id IS NULL OR merged_into_venue_id <> id);

CREATE TABLE public.venue_name_versions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id integer NOT NULL
        REFERENCES public.venue_list(id) ON DELETE RESTRICT,
    venue_name text NOT NULL,
    valid_from date,
    valid_to date,
    CONSTRAINT venue_name_versions_name_not_blank
        CHECK (btrim(venue_name) <> ''),
    CONSTRAINT venue_name_versions_valid_range
        CHECK (valid_to IS NULL OR valid_from IS NULL OR valid_to > valid_from),
    CONSTRAINT venue_name_versions_venue_id_id_unique
        UNIQUE (venue_id, id)
);

CREATE UNIQUE INDEX venue_name_versions_one_open_idx
    ON public.venue_name_versions (venue_id)
    WHERE valid_to IS NULL;

CREATE INDEX venue_name_versions_lookup_idx
    ON public.venue_name_versions (lower(btrim(venue_name)), venue_id);

CREATE INDEX venue_name_versions_validity_idx
    ON public.venue_name_versions (venue_id, valid_from, valid_to, id);

INSERT INTO public.venue_name_versions (venue_id, venue_name, valid_from, valid_to)
SELECT id, venue, NULL, NULL
FROM public.venue_list
ORDER BY id;

ALTER TABLE public.live_attrs
    ADD COLUMN venue_name_version_id bigint
        REFERENCES public.venue_name_versions(id) ON DELETE RESTRICT;

UPDATE public.live_attrs live
SET venue_name_version_id = version.id
FROM public.venue_name_versions version
WHERE version.venue_id = live.venue_id
  AND version.valid_to IS NULL;

ALTER TABLE public.live_schedule_history
    ADD COLUMN previous_venue_name_version_id bigint
        REFERENCES public.venue_name_versions(id) ON DELETE RESTRICT;

UPDATE public.live_schedule_history history
SET previous_venue_name_version_id = version.id
FROM public.venue_name_versions version
WHERE version.venue_id = history.previous_venue_id
  AND version.valid_to IS NULL;

CREATE INDEX live_attrs_venue_name_version_idx
    ON public.live_attrs (venue_name_version_id)
    WHERE venue_name_version_id IS NOT NULL;

CREATE INDEX live_schedule_history_venue_name_version_idx
    ON public.live_schedule_history (previous_venue_name_version_id)
    WHERE previous_venue_name_version_id IS NOT NULL;

CREATE VIEW public.current_venue_versions AS
SELECT
    venue.id AS venue_id,
    version.venue_name,
    version.id AS venue_name_version_id,
    venue.venue_kind,
    venue.merged_into_venue_id
FROM public.venue_list venue
JOIN public.venue_name_versions version
  ON version.venue_id = venue.id
 AND version.valid_to IS NULL
WHERE venue.merged_into_venue_id IS NULL;

RESET ROLE;

GRANT SELECT ON TABLE
    public.venue_name_versions,
    public.current_venue_versions
TO live_project_ro, live_project_super_ro;

GRANT INSERT, UPDATE ON TABLE
    public.venue_name_versions
TO live_project_super_ro;

GRANT USAGE, SELECT, UPDATE ON SEQUENCE
    public.venue_name_versions_id_seq
TO live_project_super_ro;
