SET ROLE live_project_owner;

CREATE TABLE public.geo_localities (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code text NOT NULL CHECK (country_code ~ '^[A-Z]{2}$'),
    admin_area text,
    locality_name text NOT NULL CHECK (btrim(locality_name) <> ''),
    timezone_id text,
    revision integer NOT NULL DEFAULT 1 CHECK (revision > 0)
);

ALTER TABLE public.venue_list
    ADD COLUMN locality_id integer REFERENCES public.geo_localities(id) ON DELETE RESTRICT,
    ADD COLUMN address text,
    ADD COLUMN latitude numeric(9,6),
    ADD COLUMN longitude numeric(10,6),
    ADD COLUMN timezone_id text,
    ADD COLUMN location_revision integer NOT NULL DEFAULT 1 CHECK (location_revision > 0),
    ADD COLUMN location_verified_at timestamptz,
    ADD CONSTRAINT venue_coordinates_pair CHECK ((latitude IS NULL) = (longitude IS NULL)),
    ADD CONSTRAINT venue_latitude_range CHECK (latitude BETWEEN -90 AND 90),
    ADD CONSTRAINT venue_longitude_range CHECK (longitude BETWEEN -180 AND 180),
    ADD CONSTRAINT venue_online_location_empty CHECK (
        venue_kind <> 'online' OR
        (locality_id IS NULL AND address IS NULL AND latitude IS NULL AND longitude IS NULL AND timezone_id IS NULL)
    ),
    ADD CONSTRAINT venue_precise_timezone_requires_point CHECK (timezone_id IS NULL OR latitude IS NOT NULL);

CREATE INDEX venue_list_locality_idx ON public.venue_list(locality_id);

CREATE TABLE public.venue_map_links (
    venue_id integer NOT NULL REFERENCES public.venue_list(id) ON DELETE RESTRICT,
    provider text NOT NULL CHECK (provider IN ('google', 'apple', 'amap')),
    provider_place_id text,
    provider_url text,
    location_revision integer NOT NULL CHECK (location_revision > 0),
    verified_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (venue_id, provider),
    CONSTRAINT venue_map_link_target CHECK (
        NULLIF(btrim(provider_place_id), '') IS NOT NULL OR NULLIF(btrim(provider_url), '') IS NOT NULL
    )
);

RESET ROLE;

GRANT SELECT ON public.geo_localities, public.venue_map_links TO live_project_ro, live_project_super_ro;
GRANT INSERT, UPDATE ON public.geo_localities, public.venue_map_links TO live_project_super_ro;
GRANT DELETE ON public.venue_map_links TO live_project_super_ro;
GRANT USAGE, SELECT ON SEQUENCE public.geo_localities_id_seq TO live_project_super_ro;
