SET ROLE live_project_owner;

CREATE TABLE public.live_timezone_review_resolutions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    live_id integer NOT NULL REFERENCES public.live_attrs(id) ON DELETE RESTRICT,
    decision text NOT NULL CHECK (decision IN ('retain', 'apply_current')),
    snapshot_timezone_id text NOT NULL,
    snapshot_source_revision integer,
    target_timezone_id text NOT NULL,
    target_source_revision integer NOT NULL CHECK (target_source_revision > 0),
    reason text,
    decided_by bigint REFERENCES public.app_users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT live_timezone_review_retain_reason CHECK (
        decision <> 'retain' OR NULLIF(btrim(reason), '') IS NOT NULL
    )
);

CREATE UNIQUE INDEX live_timezone_review_active_retain_uq
    ON public.live_timezone_review_resolutions (
        live_id,
        snapshot_timezone_id,
        COALESCE(snapshot_source_revision, 0),
        target_timezone_id,
        target_source_revision
    )
    WHERE decision = 'retain';

CREATE INDEX live_timezone_review_live_idx
    ON public.live_timezone_review_resolutions (live_id, created_at DESC);

RESET ROLE;

GRANT SELECT ON public.live_timezone_review_resolutions TO live_project_ro, live_project_super_ro;
GRANT INSERT ON public.live_timezone_review_resolutions TO live_project_super_ro;
GRANT USAGE, SELECT ON SEQUENCE public.live_timezone_review_resolutions_id_seq TO live_project_super_ro;
