SET ROLE live_project_owner;

CREATE TABLE public.song_groups (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_name text NOT NULL CHECK (btrim(group_name) <> ''),
    revision bigint NOT NULL DEFAULT 1
);
ALTER TABLE public.song_list
    ADD COLUMN group_id integer REFERENCES public.song_groups(id),
    ADD COLUMN version_label text NOT NULL DEFAULT '',
    ADD COLUMN version_order integer NOT NULL DEFAULT 1 CHECK (version_order > 0),
    ADD COLUMN owner_mode text CHECK (owner_mode IN ('bands', 'members')),
    ADD COLUMN revision bigint NOT NULL DEFAULT 1,
    ALTER COLUMN band_id DROP NOT NULL;

-- Mechanical singleton groups preserve song identities; ownership awaits reviewed backfill.
INSERT INTO public.song_groups(id, group_name) SELECT id, song_name FROM public.song_list;
SELECT setval(pg_get_serial_sequence('public.song_groups', 'id'),
              GREATEST(COALESCE((SELECT max(id) FROM public.song_groups), 0), 1),
              EXISTS (SELECT 1 FROM public.song_groups));
UPDATE public.song_list SET group_id = id;
ALTER TABLE public.song_list ALTER COLUMN group_id SET NOT NULL;
CREATE INDEX song_list_group_idx ON public.song_list(group_id, version_order, id);

CREATE TABLE public.members (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 68) PRIMARY KEY,
    display_name text NOT NULL CHECK (btrim(display_name) <> ''),
    revision bigint NOT NULL DEFAULT 1
);
-- IDs 1..67 are reserved for the approved manual member backfill.

CREATE TABLE public.song_bands (
    song_id integer NOT NULL REFERENCES public.song_list(id) ON DELETE CASCADE,
    band_id integer NOT NULL REFERENCES public.band_attrs(id),
    display_order integer NOT NULL CHECK (display_order > 0),
    PRIMARY KEY (song_id, band_id)
);
CREATE TABLE public.song_member_groups (
    song_id integer NOT NULL REFERENCES public.song_list(id) ON DELETE CASCADE,
    band_id integer NOT NULL REFERENCES public.band_attrs(id),
    display_order integer NOT NULL CHECK (display_order > 0),
    PRIMARY KEY (song_id, band_id)
);
CREATE TABLE public.song_members (
    song_id integer NOT NULL,
    band_id integer NOT NULL,
    member_id integer NOT NULL REFERENCES public.members(id),
    display_order integer NOT NULL CHECK (display_order > 0),
    PRIMARY KEY (song_id, member_id),
    FOREIGN KEY (song_id, band_id) REFERENCES public.song_member_groups(song_id, band_id)
        ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
ALTER TABLE public.band_lineup_version_members ADD COLUMN member_id integer REFERENCES public.members(id);
ALTER TABLE public.live_setlist_band_performance_members ADD COLUMN member_id integer REFERENCES public.members(id);

CREATE TABLE public.albums (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_name text NOT NULL CHECK (btrim(album_name) <> ''),
    release_label text NOT NULL DEFAULT '',
    release_date date,
    cover_path text,
    revision bigint NOT NULL DEFAULT 1
);
CREATE TABLE public.album_tracks (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id integer NOT NULL REFERENCES public.albums(id) ON DELETE CASCADE,
    song_id integer NOT NULL REFERENCES public.song_list(id),
    track_order integer NOT NULL CHECK (track_order > 0),
    edition_label text NOT NULL DEFAULT '',
    UNIQUE (album_id, track_order) DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX album_tracks_song_idx ON public.album_tracks(song_id);
CREATE INDEX song_bands_band_idx ON public.song_bands(band_id, song_id);
CREATE INDEX song_member_groups_band_idx ON public.song_member_groups(band_id, song_id);

-- Every relation edit takes the same parent lock before the deferred invariant check.
CREATE FUNCTION public.lock_song_ownership() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF TG_OP = 'UPDATE' AND OLD.song_id <> NEW.song_id THEN
        RAISE EXCEPTION 'Move ownership using delete and insert' USING ERRCODE = '23514';
    END IF;
    IF TG_OP <> 'INSERT' THEN
        PERFORM 1 FROM public.song_list WHERE id = OLD.song_id FOR UPDATE;
    END IF;
    IF TG_OP <> 'DELETE' THEN
        PERFORM 1 FROM public.song_list WHERE id = NEW.song_id FOR UPDATE;
        RETURN NEW;
    END IF;
    RETURN OLD;
END $$;
CREATE FUNCTION public.check_song_ownership() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target integer; mode text; has_bands boolean; has_groups boolean;
BEGIN
    IF TG_TABLE_NAME = 'song_list' THEN target := NEW.id;
    ELSIF TG_OP = 'DELETE' THEN target := OLD.song_id;
    ELSE target := NEW.song_id;
    END IF;
    SELECT owner_mode INTO mode FROM public.song_list WHERE id = target;
    IF NOT FOUND THEN RETURN NULL; END IF;
    SELECT EXISTS(SELECT 1 FROM public.song_bands WHERE song_id = target),
           EXISTS(SELECT 1 FROM public.song_member_groups WHERE song_id = target)
    INTO has_bands, has_groups;
    IF (mode IS NULL AND (has_bands OR has_groups))
       OR (mode = 'bands' AND (NOT has_bands OR has_groups))
       OR (mode = 'members' AND (has_bands OR NOT has_groups))
       OR EXISTS(SELECT 1 FROM public.song_member_groups g WHERE g.song_id = target
                 AND NOT EXISTS(SELECT 1 FROM public.song_members m
                                WHERE m.song_id = g.song_id AND m.band_id = g.band_id)) THEN
        RAISE EXCEPTION 'Invalid ownership for song %', target USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER song_ownership_check AFTER INSERT OR UPDATE ON public.song_list
    DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.check_song_ownership();
DO $$ DECLARE relation text; BEGIN
    FOREACH relation IN ARRAY ARRAY['song_bands', 'song_member_groups', 'song_members'] LOOP
        EXECUTE format('CREATE TRIGGER song_ownership_lock BEFORE INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.lock_song_ownership()', relation);
        EXECUTE format('CREATE CONSTRAINT TRIGGER song_ownership_check AFTER INSERT OR UPDATE OR DELETE ON public.%I DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.check_song_ownership()', relation);
    END LOOP;
END $$;

GRANT SELECT ON public.song_groups, public.members, public.song_bands, public.song_member_groups,
    public.song_members, public.albums, public.album_tracks TO live_project_ro, live_project_user_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.song_groups, public.members, public.song_bands,
    public.song_member_groups, public.song_members, public.albums, public.album_tracks TO live_project_super_ro;
GRANT USAGE, SELECT ON SEQUENCE public.song_groups_id_seq, public.members_id_seq,
    public.albums_id_seq, public.album_tracks_id_seq TO live_project_super_ro;
RESET ROLE;
