SET ROLE live_project_owner;

ALTER TABLE public.live_setlist ADD COLUMN song_group_id integer REFERENCES public.song_groups(id);
UPDATE public.live_setlist st SET song_group_id = s.group_id FROM public.song_list s WHERE s.id = st.song_id;
ALTER TABLE public.live_setlist ALTER COLUMN song_group_id SET NOT NULL,
    ALTER COLUMN song_id DROP NOT NULL;
COMMENT ON COLUMN public.live_setlist.song_id IS 'Legacy source version only; new setlists use song_group_id.';
CREATE INDEX live_setlist_song_group_idx ON public.live_setlist(song_group_id);

ALTER TABLE public.song_list DROP CONSTRAINT song_list_song_name_band_id_key;
ALTER TABLE public.song_list DROP CONSTRAINT song_list_owner_mode_check;
ALTER TABLE public.song_list ADD CONSTRAINT song_list_owner_mode_check CHECK(owner_mode IN ('bands', 'members', 'mixed'));
CREATE OR REPLACE FUNCTION public.check_song_ownership() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target integer; mode text; has_bands boolean; has_groups boolean;
BEGIN
    IF TG_TABLE_NAME = 'song_list' THEN target := NEW.id;
    ELSIF TG_OP = 'DELETE' THEN target := OLD.song_id;
    ELSE target := NEW.song_id; END IF;
    SELECT owner_mode INTO mode FROM public.song_list WHERE id = target;
    IF NOT FOUND THEN RETURN NULL; END IF;
    SELECT EXISTS(SELECT 1 FROM public.song_bands WHERE song_id = target),
           EXISTS(SELECT 1 FROM public.song_member_groups WHERE song_id = target)
      INTO has_bands, has_groups;
    IF (mode IS NULL AND (has_bands OR has_groups))
       OR (mode = 'bands' AND (NOT has_bands OR has_groups))
       OR (mode = 'members' AND (has_bands OR NOT has_groups))
       OR (mode = 'mixed' AND (NOT has_bands OR NOT has_groups))
       OR EXISTS(SELECT 1 FROM public.song_member_groups g WHERE g.song_id = target AND NOT EXISTS(
           SELECT 1 FROM public.song_members m WHERE m.song_id = g.song_id AND m.band_id = g.band_id)) THEN
        RAISE EXCEPTION 'Invalid ownership for song %', target USING ERRCODE = '23514';
    END IF;
    RETURN NULL;
END $$;

CREATE TABLE public.album_sections (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id integer NOT NULL REFERENCES public.albums(id) ON DELETE CASCADE,
    section_name text NOT NULL DEFAULT '',
    display_order integer NOT NULL CHECK(display_order > 0),
    UNIQUE(album_id, section_name) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE(album_id, display_order) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE(id, album_id)
);
INSERT INTO public.album_sections(album_id, section_name, display_order) SELECT id, '', 1 FROM public.albums;
ALTER TABLE public.album_tracks ADD COLUMN section_id integer;
UPDATE public.album_tracks t SET section_id = s.id FROM public.album_sections s WHERE s.album_id = t.album_id;
ALTER TABLE public.album_tracks ALTER COLUMN section_id SET NOT NULL,
    DROP CONSTRAINT album_tracks_album_id_track_order_key,
    ADD FOREIGN KEY(section_id, album_id) REFERENCES public.album_sections(id, album_id),
    ADD UNIQUE(section_id, track_order) DEFERRABLE INITIALLY DEFERRED;

GRANT SELECT ON public.album_sections TO live_project_ro;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.album_sections TO live_project_super_ro;
GRANT USAGE, SELECT ON SEQUENCE public.album_sections_id_seq TO live_project_super_ro;
RESET ROLE;
